name: Benchmark
on:
  workflow_dispatch:
    inputs:
      filter:
        description: Filter which benchmarks to run with a wildcard.
        required: false
        default: '*'
jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Run benchmarks
        run: dotnet run --project tests/Recursiont.Benchmarks/Recursiont.Benchmarks.csproj -c Release -- -f "${{ inputs.filter }}" -e github -a ./benchmark-artifacts/
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-artifacts
          path: ./benchmark-artifacts
